### PR TITLE
Fixed input 'append' and 'prepend', badge-styles

### PR DESCRIPTION
**Pull request by manuelfischer**
I don't exactly understood what happened in _combine_input($options), i hope i got this right - at least 'append' and 'prepend' works for me now.

### CODE REVIEW

**Comment by joeytrapp** [comment]
Please run the test suite and make sure you've made the changes there to reflect the badge style changes.

I'm going to look more closely at 30b19e5 and 7797db4 before merging.

Thanks.

**Comment by manuelfischer** [comment]
sorry, totally forgot about that.
Test cases are added now, i hope i did this correct.

Also passing "field" to FormHelper results in invalid HTML (and test fails)!

**Comment by joeytrapp** [comment]
I'm still looking over the commits and figuring out how I'm going to merge in.

The append/prepend functionality wasn't ever flushed out fully (it is on my todo list). I noticed a few things that you've removed that actually need to be there to cover all the append/prepend functionality as the bootstrap docs detail it.

I'm probably going to merge your commits into the 2.0 branch (or a new feature branch) and wait to merge that into master until it is all fixed and has supporting tests.

**Comment by manuelfischer** [comment]
As mentioned I didn't understand the logic in _combine_input(), but the function gets called anyway and doesn't do what expected. I tried to fix it - it works for me with this pull request and all tests pass now.

If you don't want to merge it, you should consider taking a look at d075720 and 396f038, without them some tests fail, badge style 'badge-error' does not exist and generated inputs are invalid (passing 'field' to form helper)

**Comment by joeytrapp** [comment]
I'm going to pull this into a feature branch and then cherry pick those commits out into 2.0/master.

One thing that will still need to be worked on is that if you pass an input for the append/prepend content, the wrapping tag needs to be a label. Based on one of the commits, it looks like this was removed. That was just one thing I saw.

**Comment by joeytrapp** [comment]
I've created a branch 2.0-input where your commits have been merged into. I'm going to continue working there to get the edge cases of the append/prepend stuff, so if you have more code to add, open the pull request on that branch.

I'm going to cherry pick the commits that fixed badge and the field options into 2.0 and master after reviewing some.

Thanks for your contributions!

**Pull request closed without merging**
